### PR TITLE
branch "msvc"

### PR DESCRIPTION
**Pull request by stnoh**
- few updates for MSVC compilation
- project "pySequentialLineSearch": python binding (experimental)

### CODE REVIEW

**Comment by yuki-koyama** [comment]
Thank you for the PR! In my understanding, this PR consists of the following 4 useful improvements:

- Resolving OpenGL issues by using GLEW (for Windows)
- Integrating pybind11
- Resolving Qt5 link issues (for Windows)
- Fix general bugs (e.g., including a missing header)

All of them are great, but probably the OpenGL one has been already fixed or needs a different solution because of a very recent commit: https://github.com/yuki-koyama/sequential-line-search/commit/9c26df7ff1fac8b482cac1b97df844be20e0e195 .

Could you check it and send separate PRs? Or, if you do not mind, I will merge the current PR with manually rewinding the changes about the OpenGL issue.

**Comment by stnoh** [comment]
Oh, master branch was updated recently. I didn't notice that.
Well, I think the issue is in commit: 1b9364b .
If you want separete PRs, maybe I can create 
- PR(1) for MSVC fixes (merge 5d5950b and bfade6d) as separete branch (e.g. Branch_msvc),
- PR(2) for experimental python binding in master branch (or another branch?)

Is it ok for you?

**Comment by yuki-koyama** [comment]
> Is it ok for you?

Yes, completely fine. Thank you for your proposal and sorry for my bad-timing updates.

**Comment by stnoh** [comment]
To avoid confusion, I removed this branch and created other pull requests.

**Pull request closed without merging**
